apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: default
spec:
  commonName: traefik.adadeeeh.com
  secretName: nginx-cert
  dnsNames:
    - traefik.adadeeeh.com
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
